# Artificial Neural Network

### Importing the libraries

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [15]:
dataset = pd.read_csv("/content/Churn_Modelling.csv")
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [29]:
dataset.shape

(10000, 14)

In [44]:
 dataset.iloc[:,3:-1]

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France  Female  ...          1               1        101348.88
1             608     Spain  Female  ...          0               1        112542.58
2             502    France  Female  ...          1               0        113931.57
3             699    France  Female  ...          0               0         93826.63
4             850     Spain  Female  ...          1               1         79084.10
...           ...       ...     ...  ...        ...             ...              ...
9995          771    France    Male  ...          1               0         96270.64
9996          516    France    Male  ...          1               1        101699.77
9997          709    France  Female  ...          0               1         42085.58
9998          772   Germany    Male  ...          1               0         92888.52
9999          792    France  Female  ...          1               0         38190.78

[10000 rows x 10 columns]

In [17]:
y

array([1, 0, 1, ..., 1, 1, 0])

### Encoding categorical data

Label Encoding the "Gender" column

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])


In [19]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [21]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [43]:
X[0,:]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

### Splitting the dataset into the Training set and Test set

In [30]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.2,random_state=0)

In [31]:
print(X_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [32]:
print(y_train)

[0 0 0 ... 0 0 1]


In [33]:
print(X_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [34]:
print(y_test)

[0 1 0 ... 0 0 0]


### Feature Scaling

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [36]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [37]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [38]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [39]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [40]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

### Training the ANN on the Training set

In [62]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8652
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8635
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8645
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8644
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3336 - accuracy: 0.8644
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3338 - accuracy: 0.8624
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.8640
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3335 - accuracy: 0.8648
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3334 - accuracy: 0.8651
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3334 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [63]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [57]:
np.array([1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000])

array([    1,     0,     0,   600,     1,    40,     3, 60000,     2,
           1,     1, 50000])

In [58]:
np.array([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])

array([[    1,     0,     0,   600,     1,    40,     3, 60000,     2,
            1,     1, 50000]])

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [64]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1542   53]
 [ 291  114]]


0.828